// Do not edit by hand. This file generated by github.com/falun/gobundle.

package bundle

import (
	"archive/zip"
	"bytes"
	"io/ioutil"
	"os"
	"path/filepath"
)

func writeFile(path string, contents []byte) error {
	err := os.MkdirAll(filepath.Dir(path), 0744)
	if err != nil {
		return err
	}

	err = ioutil.WriteFile(path, contents, 0622)
	if err != nil {
		return err
	}

	return nil
}

func installCompressed(dir string) error {
	compressedBytes := bytes.NewReader(compressed)
	reader, err := zip.NewReader(compressedBytes, int64(compressedBytes.Len()))
	if err != nil {
		return err
	}

	for _, file := range reader.File {
		c, err := file.Open()
		if err != nil {
			return err
		}

		contents, err := ioutil.ReadAll(c)
		if err != nil {
			return err
		}

		err = writeFile(filepath.Join(dir, file.Name), contents)
		if err != nil {
			return err
		}

		c.Close()
	}

	return nil
}

func installRaw(dir string) error {
	for path, contents := range raw {
		err := writeFile(filepath.Join(dir, path), contents)
		if err != nil {
			return err
		}
	}

	return nil
}

// Install decompresses the included assets into a target directory. Any existing
// files of the same name will be overwritten.
func Install(dir string) error {
	if err := installRaw(dir); err != nil {
		return err
	}
	if err := installCompressed(dir); err != nil {
		return err
	}

	return nil
}