// Package bundle is an auto generated package that includes some static assets into
// a golang binary when built. The included Install function will extract these
// assets into a target directory.
//
// This bundle includes the following files:
//
//     - mime.json
//     - api.js
//     - browse.tmpl
//     - index.tmpl
//     - index-nav.js
//     - markup.css
//     - search.css
//     - search.js
//     - style.css
//     - vendor/bootstrap.min.css
//     - vendor/bootstrap.min.js
//     - vendor/jquery.min.js
//     - vendor/glyphicons-28-search.png
//
// Generated by github.com/falun/gobundle
package bundle
